//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresasFornecedores.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoEmpresasEntities : DbContext
    {
        public ProjetoEmpresasEntities()
            : base("name=ProjetoEmpresasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<FornecedorPF> FornecedorPF { get; set; }
        public virtual DbSet<FornecedorPJ> FornecedorPJ { get; set; }

        public System.Data.Entity.DbSet<EmpresasFornecedores.Models.EmpresaModel> EmpresaModels { get; set; }
    }
}
