//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresasFornecedores.DAL
{
    using EmpresasFornecedores.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.FornecedorPJ = new HashSet<FornecedorPJ>();
            this.FornecedorPF = new HashSet<FornecedorPF>();
        }
    
        public int Id { get; set; }
        [DisplayName("Nome Empresa")]
        public string NomeFantasia { get; set; }
        [StringLength(14, ErrorMessage = "CNPJ Inválido", MinimumLength = 14)]
        public string CNPJ { get; set; }
        [StringLength(2, ErrorMessage = "UF Inválido", MinimumLength = 2)]
        public string UF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedorPJ> FornecedorPJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedorPF> FornecedorPF { get; set; }

      
    }
    
}
