//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresasFornecedores.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FornecedorPF
    {
        public int ID { get; set; }
        [DisplayName("Indentificador Empresa Contratante")]
        public Nullable<int> EmpresaId { get; set; }
        [DisplayName("Nome")]
        public string FornecedorNome { get; set; }
        [DisplayName("CPF")]
        [StringLength(11, ErrorMessage = "Cpf inválido", MinimumLength = 11)]
        public string FornecedorCPF { get; set; }
        [DisplayName("RG")]
        [StringLength(11, ErrorMessage = "RG inválido", MinimumLength = 7)]
        public string FornecedorRG { get; set; }
        [DisplayName("Data Nascimento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DataNascimento { get; set; }
        [NotMapped]
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Telefone { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
