//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresasFornecedores.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FornecedorPJ
    {
        public int ID { get; set; }
        [NotMapped]
        public Nullable<int> EmpresaId { get; set; }
        [DisplayName("Nome")]
        public string FornecedorNome { get; set; }
        [DisplayName("CNPJ")]
        [StringLength(14,ErrorMessage ="CNPJ inválido",MinimumLength =14)]
        public string FornecedorCNPJ { get; set; }
        [NotMapped]
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Telefone { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
